version: "3.8"

services:
  web:
    build: .
    container_name: flask-web
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"

